name: snap

on:
  push:
    branches:
      - jazzy
    tags:
      - 'jazzy/*'
  pull_request:
    branches:
      - jazzy
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    with:
      runs-on: '["ubuntu-latest"]'
      snapcraft-source-subdir: "."
      snap-track: jazzy
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
